name: NPM Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Generate .npmrc
      run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

    - run: yarn
    - run: yarn build
    - run: yarn test

    - name: Publish to NPM
      run: yarn release-it --ci --npm.skipChecks
